# Module: NumPy Assignments
## Lesson: NumPy











In [9]:
### Assignment 1: Array Creation and Manipulation

#1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
import numpy as np 
nm_array=np.arange(0,25,1).reshape(5,5)
#num_array=np.random.randint(0,25, size=(5,5))
nm_array[3:4]=1
nm_array

np_array=np.random.randint(0,16,size=(4,4))
np.fill_diagonal(np_array,0)
np_array


array([[ 0, 15, 13,  5],
       [13,  0,  7,  4],
       [ 0, 12,  0, 10],
       [ 3, 10, 11,  0]], dtype=int32)

In [19]:
### Assignment 2: Array Indexing and Slicing

#1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
#2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
np_array=np.arange(1,37).reshape(6,6)
sub_array=np_array[3:6,2:5]
print(np_array)
np_array2=np.arange(1,26).reshape(5,5)
np_array2[0:5,0:5:4]




[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


array([[ 1,  5],
       [ 6, 10],
       [11, 15],
       [16, 20],
       [21, 25]])

In [29]:

### Assignment 3: Array Operations

#1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

np_array=np.arange(0,12).reshape(3,4)
np_array+10
print(np_array)
print(np.sum(np_array,axis=1))
print(np.sum(np_array,axis=0))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 6 22 38]
[12 15 18 21]


In [33]:
### Assignment 4: Statistical Operations

#1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
#2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).
from scipy import stats
np_array=np.arange(1,26).reshape(5,5)
stats.describe(np_array)
#
np_arr=np_array.ravel()
stats.describe(np_arr)

DescribeResult(nobs=25, minmax=(np.int64(1), np.int64(25)), mean=np.float64(13.0), variance=np.float64(54.16666666666667), skewness=np.float64(0.0), kurtosis=np.float64(-1.2038461538461538))

In [36]:
### Assignment 5: Broadcasting

#1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
#2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.
np_array=np.arange(0,9).reshape(3,3)
broad_cast_array=np.arange(0,3).reshape(3,)
print(np_array)
print(broad_cast_array)
np_array+broad_cast_array

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [45]:

### Assignment 6: Linear Algebra

#1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
#2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.
num_array=np.arange(0,9).reshape(3,3)
array = np.array([[4, 2],
                  [3, 1]]) 
det=np.linalg.det(array)
print(det) 
mat1=np.arange(0,6).reshape(2,3)
mat2=np.arange(0,6).reshape(3,2)
print(mat1)
print(mat2)
print(np.matmul(mat1,mat2)) 
print(mat1@mat2)




-2.0
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[10 13]
 [28 40]]
[[10 13]
 [28 40]]


In [51]:


### Assignment 7: Advanced Array Manipulation

#1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
#2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

nm_array=np.arange(0,9).reshape(3,3)
print(nm_array)
print(nm_array.reshape(9,1))
print(nm_array.reshape(1,9))

array=np.arange(1,26).reshape(5,5)
flatten=array.ravel()
print(flatten)
print(flatten.reshape(5,5))



[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[0 1 2 3 4 5 6 7 8]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [55]:


### Assignment 8: Fancy Indexing and Boolean Indexing

#1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
#2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

import numpy as np

# Create a 2D NumPy array
array = np.array([[10, 20, 30], 
                  [40, 50, 60], 
                  [70, 80, 90]])

# Use fancy indexing to extract specific elements
# Let's say we want to extract (0, 1), (1, 2), and (2, 0)
rows = [0, 1, 2]
cols = [1, 2, 0]

# Fancy indexing
result = array[rows, cols]

print("Original Array:")
print(array)
print("\nExtracted Elements:")
print(result)
array[array>10]=10
print(array)



Original Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Extracted Elements:
[20 60 70]
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [56]:

### Assignment 9: Structured Arrays

#1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
#2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.
import numpy as np

# Step 1: Define the structured array data type
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]

# Step 2: Create the structured array and add some data
people = np.array([('Alice', 25, 55.0),
                   ('Bob', 30, 78.5),
                   ('Charlie', 22, 68.1),
                   ('David', 35, 85.2)],
                  dtype=data_type)

# Step 3: Sort the array by 'age'
sorted_people = np.sort(people, order='age')

# Print the sorted array
print("Structured Array Sorted by Age:")
print(sorted_people)
data_type2 = [('x', 'i4'), ('y', 'i4')]
normal_points=np.array([(10,10),
                        (20,20),
                        (30,30)])
import numpy as np

# Step 1: Define the structured array data type
data_type = [('x', 'i4'), ('y', 'i4')]

# Step 2: Create the structured array and add some data
points = np.array([(1, 2), (4, 6), (7, 8), (2, 1)], dtype=data_type)

# Step 3: Compute Euclidean distance between each pair of points
def euclidean_distance(p1, p2):
    return np.sqrt((p1['x'] - p2['x'])**2 + (p1['y'] - p2['y'])**2)

# Step 4: Compute and print distances between all pairs of points
n_points = len(points)
distances = np.zeros((n_points, n_points))

for i in range(n_points):
    for j in range(n_points):
        distances[i, j] = euclidean_distance(points[i], points[j])

# Print the original points and their pairwise distances
print("Points:")
print(points)

print("\nEuclidean Distances:")
print(distances)



Structured Array Sorted by Age:
[('Charlie', 22, 68.1) ('Alice', 25, 55. ) ('Bob', 30, 78.5)
 ('David', 35, 85.2)]


In [57]:
### Assignment 10: Masked Arrays
import numpy.ma as ma
#1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
#2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.
array=np.arange(0,16).reshape(4,4)
masked_array=ma.masked_array(array,mask=array>4)
print(masked_array)
print(masked_array.sum())


[[0 1 2 3]
 [4 -- -- --]
 [-- -- -- --]
 [-- -- -- --]]
10
