In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
##sentences 
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
##define the vocabulary size
voc_size=10000


In [5]:
##one hot representation  
one_hot_repr=[one_hot(words,voc_size)for words in sent]

In [6]:
one_hot_repr

[[2124, 7760, 7814, 2415],
 [2124, 7760, 7814, 9281],
 [2124, 7657, 7814, 1748],
 [5690, 430, 1892, 5161, 2375],
 [5690, 430, 1892, 5161, 7470],
 [4048, 2124, 8927, 7814, 4652],
 [6819, 2082, 419, 5161]]

In [8]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences 
from tensorflow.keras.models import Sequential 

In [9]:
import numpy as np 


In [10]:
#its importnant that all sentences should have equal word lenght becuase our rnn size should be able to perform actions or time stamps 


In [12]:
sent_length=8
#making all words in sentence to 8 if its have less than 8 we are adding the empty sentence to it 
embedded_doc=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_doc)

[[   0    0    0    0 2124 7760 7814 2415]
 [   0    0    0    0 2124 7760 7814 9281]
 [   0    0    0    0 2124 7657 7814 1748]
 [   0    0    0 5690  430 1892 5161 2375]
 [   0    0    0 5690  430 1892 5161 7470]
 [   0    0    0 4048 2124 8927 7814 4652]
 [   0    0    0    0 6819 2082  419 5161]]


In [13]:
### feature represemtation
dim=10 


In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim
                    ,input_length=sent_length))
model.compile('adam','mse')
#embedding internallly uses word2vec aporach to conver int the vectors

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step


array([[[ 0.02193518,  0.00923269,  0.006778  ,  0.02607835,
         -0.04674275, -0.01611938, -0.01885225,  0.00931989,
          0.03089168,  0.03431186],
        [ 0.02193518,  0.00923269,  0.006778  ,  0.02607835,
         -0.04674275, -0.01611938, -0.01885225,  0.00931989,
          0.03089168,  0.03431186],
        [ 0.02193518,  0.00923269,  0.006778  ,  0.02607835,
         -0.04674275, -0.01611938, -0.01885225,  0.00931989,
          0.03089168,  0.03431186],
        [ 0.02193518,  0.00923269,  0.006778  ,  0.02607835,
         -0.04674275, -0.01611938, -0.01885225,  0.00931989,
          0.03089168,  0.03431186],
        [ 0.00605952, -0.01365768,  0.01444523, -0.00511932,
         -0.00531457,  0.04125794, -0.007475  ,  0.04159747,
         -0.04452752,  0.01080191],
        [ 0.03271052,  0.0175356 ,  0.00096862,  0.00962659,
         -0.02665057,  0.04194652, -0.03204068,  0.00548087,
          0.02397541,  0.0068293 ],
        [-0.03441813, -0.0060303 ,  0.00562898, -0.0

In [18]:
embedded_doc[0]

array([   0,    0,    0,    0, 2124, 7760, 7814, 2415], dtype=int32)